name: SimplyPerms
main: net.crystalyx.bukkit.simplyperms.SimplyPlugin
author: Xefir Destiny
website: http://www.crystalyx.net/
version: 1.7.1
softdepend: [ PermissionsBukkit ]
commands:
  permissions:
    aliases: [ perms, perm, p ]
    description: Commands for manipulating permissions.
    usage: |
        /<command> reload - reload the configuration from disk.
        /<command> check <node> [player] - check if a player or the sender has a permission (any plugin).
        /<command> info <node> - prints information on a specific permission.
        /<command> dump [player] [page] - prints info about a player's (or the sender's) permissions.
        /<command> import <type> - Import data from database or others permissions plugins
        /<command> group - list group-related commands.
        /<command> group list - list all groups.
        /<command> group players <group> - list players in a group.
        /<command> group setperm <group> <[world:]node> [true|false] - set a permission on a group.
        /<command> group unsetperm <group> <[world:]node> - unset a permission on a group.
        /<command> player - list player-related commands.
        /<command> player groups <player> - list groups a player is in.
        /<command> player setgroup <player> <group,...> - set a player to be in only the given groups.
        /<command> player addgroup <player> <group> - add a player to a group.
        /<command> player removegroup <player> <group> - remove a player from a group.
        /<command> player remove <player> - remove a player from config file.
        /<command> player setperm <player> <[world:]node> [true|false] - set a permission on a player.
        /<command> player unsetperm <player> <[world:]node> - unset a permission on a player.
permissions:
  permissions.*:
    default: op
    description: Allows use of all PermissionsBukkit administration commands.
    children:
      permissions.help: true
      permissions.reload: true
      permissions.check: true
      permissions.info: true
      permissions.dump: true
      permissions.import: true
      permissions.group.*: true
      permissions.player.*: true
      permissions.allow.*: true
  permissions.help:
    description: Allows viewing of usage for /permissions.
  permissions.reload:
    description: Allows use of /permissions reload.
  permissions.check:
    description: Allows use of /permissions check.
  permissions.info:
    description: Allows use of /permissions info.
  permissions.dump:
    description: Allows use of /permissions dump.
  permissions.import:
    description: Allows use of /permissions import.
  permissions.group.*:
    description: Allows use of all /permissions group commands.
    children:
      permissions.group.help: true
      permissions.group.list: true
      permissions.group.players: true
      permissions.group.setperm: true
      permissions.group.unsetperm: true
  permissions.group.help:
    description: Allows viewing of usage for /permissions group.
  permissions.group.list:
    description: Allows use of /permissions group list.
  permissions.group.players:
    description: Allows use of /permissions group players.
  permissions.group.setperm:
    description: Allows use of /permissions group setperm.
  permissions.group.unsetperm:
    description: Allows use of /permissions group unsetperm.
  permissions.player.*:
    description: Allows use of all /permissions player commands.
    children:
      permissions.player.help: true
      permissions.player.groups: true
      permissions.player.setgroup: true
      permissions.player.addgroup: true
      permissions.player.removegroup: true
      permissions.player.remove: true
      permissions.player.setperm: true
      permissions.player.unsetperm: true
  permissions.player.help:
    description: Allows viewing of usage for /permissions player.
  permissions.player.groups:
    description: Allows use of /permissions player groups.
  permissions.player.setgroup:
    description: Allows use of /permissions player setgroup.
  permissions.player.addgroup:
    description: Allows use of /permissions player addgroup.
  permissions.player.removegroup:
    description: Allows use of /permissions player removegroup.
  permissions.player.remove:
    description: Allows use of /permissions player remove.
  permissions.player.setperm:
    description: Allows use of /permissions player setperm.
  permissions.player.unsetperm:
    description: Allows use of /permissions player unsetperm.
  permissions.allow.*:
    description: Allows player to do everything.
    default: true
    children:
      permissions.allow.bow: true
      permissions.allow.changesign: true
      permissions.allow.command: true
      permissions.allow.damage: true
      permissions.allow.fight: true
      permissions.allow.hunger: true
      permissions.allow.item: true
      permissions.allow.monster: true
      permissions.allow.sneak: true
      permissions.allow.build: true
      permissions.allow.chat: true
      permissions.allow.craft: true
      permissions.allow.interact: true
      permissions.allow.loot: true
      permissions.allow.projectile: true
      permissions.allow.vehicle: true
  permissions.allow.bow:
    description: Allows the player to shoot bows
  permissions.allow.changesign:
    description: Allows the player to change signs
  permissions.allow.chat:
    description: Allows the player to chat
  permissions.allow.command:
    description: Allows the player to use all commands
  permissions.allow.damage:
    description: Allows the player to be damaged by anything
  permissions.allow.fight:
    description: Allows the player to fight
  permissions.allow.hunger:
    description: Allows the player to die by hunger
  permissions.allow.item:
    description: Allows the player to do item related things
  permissions.allow.monster:
    description: Allows the player to get targeted by mosters
  permissions.allow.sneak:
    description: Allows the player to sneak except in creative mode
  permissions.allow.build:
    description: Allows the player to build
    children:
      permissions.allow.placeblock: true
      permissions.allow.breakblock: true
  permissions.allow.placeblock:
    decription: Allows the player to place blocks
  permissions.allow.breakblock:
    description: Allows the player to break blocks
  permissions.allow.craft:
    description: Allows the player to do crafting related things
    children:
      permissions.allow.brew: true
      permissions.allow.chest: true
      permissions.allow.dispenser: true
      permissions.allow.enchant: true
      permissions.allow.furnace: true
      permissions.allow.workbench: true
  permissions.allow.brew:
    description: Allows the player to brew
  permissions.allow.chest:
    description: Allows the player to use chests
  permissions.allow.dispenser:
    description: Allows the player to dispense
  permissions.allow.enchant:
    description: Allows the player to enchant
  permissions.allow.furnace:
    description: Allows the player to furnace
  permissions.allow.workbench:
    description: Allows the player to craft
  permissions.allow.interact:
    description: Allows the player to interact with the world
    children:
      permissions.allow.bed: true
      permissions.allow.button: true
      permissions.allow.cake: true
      permissions.allow.door: true
      permissions.allow.fish: true
      permissions.allow.jukebox: true
      permissions.allow.lever: true
      permissions.allow.noteblocks: true
      permissions.allow.pressureplate: true
      permissions.allow.repeater: true
      permissions.allow.animals: true
      permissions.allow.bucket: true
      permissions.allow.fire: true
  permissions.allow.bed:
    description: Allows the player to sleep in beds
  permissions.allow.button:
    description: Allows the player to push buttons
  permissions.allow.cake:
    description: Allows the player to eat cake
  permissions.allow.door:
    description: Allows the player to open and close doors
  permissions.allow.fish:
    description: Allows the player to fish
  permissions.allow.jukebox:
    description: Allows the player to use jukebox
  permissions.allow.lever:
    description: Allows the player to use levers
  permissions.allow.noteblocks:
    description: Allows the player to change noteblocks
  permissions.allow.pressureplate:
    description: Allows the player to trigger pressure plates
  permissions.allow.repeater:
    description: Allows the player to change repeater delays
  permissions.allow.animals:
    description: Allows the player to interact with animals
    children:
      permissions.allow.shear: true
      permissions.allow.tame: true
  permissions.allow.shear:
    description: Allows the player to shear animals
  permissions.allow.tame:
    description: Allows the player to tame animals
  permissions.allow.bucket:
    description: Allows the player to use buckets
    children:
      permissions.allow.waterbucket: true
      permissions.allow.lavabucket: true
      permissions.allow.milking: true
  permissions.allow.waterbucket:
    description: Allows the player to use water buckets
  permissions.allow.lavabucket:
    description: Allows the player to use lava buckets
  permissions.allow.milking:
    description: Allows the player to fill buckets with milk
  permissions.allow.fire:
    description: Allows the player to make fire
    children:
      permissions.allow.fireball: true
      permissions.allow.flintandsteel: true
  permissions.allow.fireball:
    description: Allows the player to use fireball
  permissions.allow.flintandsteel:
    description: Allows the player to use flint and steel
  permissions.allow.loot:
    description: Allows the player to drop and pickup items
    children:
      permissions.allow.drop: true
      permissions.allow.pickup: true
  permissions.allow.drop:
    description: Allows the player to drop items
  permissions.allow.pickup:
    description: Allows the player to pickup items
  permissions.allow.chat:
    description: Allows the player to chat
    children:
      permissions.allow.spam: true
  permissions.allow.spam:
    description: Allows the player to spam
    children:
      permissions.allow.capslock: true
      permissions.allow.flood: true
  permissions.allow.capslock:
    description: ALLOWS THE PLAYER TO USE CAPSLOCK
  permissions.allow.flood:
    description: Allows the player to chat as fast as he wants
  permissions.allow.projectile:
    description: Allows the player to throw items
    children:
      permissions.allow.egg: true
      permissions.allow.potion: true
      permissions.allow.snowball: true
      permissions.allow.enderpearl: true
  permissions.allow.vehicle:
    description: Allows the player to use vehicles
    children:
      permissions.allow.vehicle.collision: true
      permissions.allow.vehicle.destroy: true
      permissions.allow.vehicle.enter: true
      permissions.allow.vehicle.place: true
  permissions.allow.vehicle.collision:
    description: Allows the player to collide with vehicles
  permissions.allow.vehicle.destroy:
    description: Allows the player to destroy vehicles
  permissions.allow.vehicle.enter:
    description: Allows the player to enter into vehicles
  permissions.allow.vehicle.place:
    description: Allows the player to place vehicles
